### ISSUE TITLE
Star button not working perfectly in a few schools 

### ISSUE THREAD

**Issue by zhuxingjie** [geoffreylitt/lucky8#37]
On "Match Charter Public Schools " page, when clicking on "star" button of the summary page, the top left of the the "Star" button didn't respond to mouse hover and click.

Possible reason for the issue: the name of the school is long and the padding of the school name overlap with the "Star" button.

![screen shot 2015-09-12 at 8 35 57 pm](https://cloud.githubusercontent.com/assets/1851225/9834580/2c0778ee-598e-11e5-9287-80381fc46e7b.png)

**Comment by geoffreylitt** [comment]
Thanks for the report, should be fixed

**Comment by zhuxingjie** [comment]
yes!
